//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSIProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSIProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado do artigo.
        /// </summary>
        public static string ArticleStatus_Auction {
            get {
                return ResourceManager.GetString("ArticleStatus_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão.
        /// </summary>
        public static string Auction_Picture {
            get {
                return ResourceManager.GetString("Auction_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão.
        /// </summary>
        public static string Auction_ReportedAuction {
            get {
                return ResourceManager.GetString("Auction_ReportedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão.
        /// </summary>
        public static string Auction_Sale {
            get {
                return ResourceManager.GetString("Auction_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprador.
        /// </summary>
        public static string Buyer_ConfirmSale {
            get {
                return ResourceManager.GetString("Buyer_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprador.
        /// </summary>
        public static string Buyer_Sale {
            get {
                return ResourceManager.GetString("Buyer_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprador confirmado.
        /// </summary>
        public static string BuyerConfirmed_ConfirmSale {
            get {
                return ResourceManager.GetString("BuyerConfirmed_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da data de compra.
        /// </summary>
        public static string BuyerDateConfirmation_ConfirmSale {
            get {
                return ResourceManager.GetString("BuyerDateConfirmation_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço compra direta.
        /// </summary>
        public static string BuyNowPrice_Auction {
            get {
                return ResourceManager.GetString("BuyNowPrice_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Category_Auction {
            get {
                return ResourceManager.GetString("Category_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code_AccountViewModels {
            get {
                return ResourceManager.GetString("Code_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Confirmação.
        /// </summary>
        public static string ConfirmationCode_ConfirmSale {
            get {
                return ResourceManager.GetString("ConfirmationCode_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar password.
        /// </summary>
        public static string ConfirmPassword_AccountViewModels {
            get {
                return ResourceManager.GetString("ConfirmPassword_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Venda.
        /// </summary>
        public static string ConfirmSale_Sale {
            get {
                return ResourceManager.GetString("ConfirmSale_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato errado! O formato correto 111111111,11.
        /// </summary>
        public static string CurrencyFormat {
            get {
                return ResourceManager.GetString("CurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um valor monetário.
        /// </summary>
        public static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date_ReportedAuctions {
            get {
                return ResourceManager.GetString("Date_ReportedAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma data..
        /// </summary>
        public static string DateType {
            get {
                return ResourceManager.GetString("DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição de entrega.
        /// </summary>
        public static string DeliveryCondition_Auction {
            get {
                return ResourceManager.GetString("DeliveryCondition_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Description_Auction {
            get {
                return ResourceManager.GetString("Description_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description_FeedbackItem {
            get {
                return ResourceManager.GetString("Description_FeedbackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description_PointsTable {
            get {
                return ResourceManager.GetString("Description_PointsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda direta.
        /// </summary>
        public static string DirectSell_Auction {
            get {
                return ResourceManager.GetString("DirectSell_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_AccountViewModels {
            get {
                return ResourceManager.GetString("Email_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Fim.
        /// </summary>
        public static string EndDate_Auction {
            get {
                return ResourceManager.GetString("EndDate_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extendido.
        /// </summary>
        public static string Extended_Auction {
            get {
                return ResourceManager.GetString("Extended_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma frase com um comprimento máximo de {1}..
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma frase com um comprimento mínimo de {2} e um comprimento máximo de {1}.
        /// </summary>
        public static string LengthMinimum {
            get {
                return ResourceManager.GetString("LengthMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Mínimo.
        /// </summary>
        public static string LowValue_BidIncrement {
            get {
                return ResourceManager.GetString("LowValue_BidIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Máximo.
        /// </summary>
        public static string MaxValue_BidIncrement {
            get {
                return ResourceManager.GetString("MaxValue_BidIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço Mínimo.
        /// </summary>
        public static string MinPrice_Auction {
            get {
                return ResourceManager.GetString("MinPrice_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Motive_ReportedAuction {
            get {
                return ResourceManager.GetString("Motive_ReportedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name_AccountViewModels {
            get {
                return ResourceManager.GetString("Name_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão.
        /// </summary>
        public static string Name_Auction {
            get {
                return ResourceManager.GetString("Name_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de incremento da licitação.
        /// </summary>
        public static string Name_BidValueInc {
            get {
                return ResourceManager.GetString("Name_BidValueInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name_Category {
            get {
                return ResourceManager.GetString("Name_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concelho.
        /// </summary>
        public static string Name_County {
            get {
                return ResourceManager.GetString("Name_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string Name_District {
            get {
                return ResourceManager.GetString("Name_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freguesia.
        /// </summary>
        public static string Name_Locality {
            get {
                return ResourceManager.GetString("Name_Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string Name_PostalCode {
            get {
                return ResourceManager.GetString("Name_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name_Tag {
            get {
                return ResourceManager.GetString("Name_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string Name_User {
            get {
                return ResourceManager.GetString("Name_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Pontos.
        /// </summary>
        public static string Number_PointsTable {
            get {
                return ResourceManager.GetString("Number_PointsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem.
        /// </summary>
        public static string Order_Picture {
            get {
                return ResourceManager.GetString("Order_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Superior.
        /// </summary>
        public static string Parent_Category {
            get {
                return ResourceManager.GetString("Parent_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_AccountViewModels {
            get {
                return ResourceManager.GetString("Password_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é diferente da password de confirmação.
        /// </summary>
        public static string PasswordType {
            get {
                return ResourceManager.GetString("PasswordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho.
        /// </summary>
        public static string Path_Picture {
            get {
                return ResourceManager.GetString("Path_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografia.
        /// </summary>
        public static string Photo_AccountViewModels {
            get {
                return ResourceManager.GetString("Photo_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string PostalCode_Auction {
            get {
                return ResourceManager.GetString("PostalCode_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato errado! O formato correto é 1111-111.
        /// </summary>
        public static string PostalCodeFormat {
            get {
                return ResourceManager.GetString("PostalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve estar entre {1} e {2}..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se do browser.
        /// </summary>
        public static string RememberBrowser_AccountViewModels {
            get {
                return ResourceManager.GetString("RememberBrowser_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se de mim.
        /// </summary>
        public static string RememberMe_AccountViewModels {
            get {
                return ResourceManager.GetString("RememberMe_AccountViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportado por.
        /// </summary>
        public static string ReportedBy_ReportedAuction {
            get {
                return ResourceManager.GetString("ReportedBy_ReportedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Seller_ConfirmSale {
            get {
                return ResourceManager.GetString("Seller_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Seller_Sale {
            get {
                return ResourceManager.GetString("Seller_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor confirmado.
        /// </summary>
        public static string SellerConfirmed_ConfirmSale {
            get {
                return ResourceManager.GetString("SellerConfirmed_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da data de venda.
        /// </summary>
        public static string SellerDateConfirmation_ConfirmSale {
            get {
                return ResourceManager.GetString("SellerDateConfirmation_ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condições de porte.
        /// </summary>
        public static string ShipmentCondition_Auction {
            get {
                return ResourceManager.GetString("ShipmentCondition_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Início.
        /// </summary>
        public static string StartDate_Auction {
            get {
                return ResourceManager.GetString("StartDate_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço inicial.
        /// </summary>
        public static string StartingPrice_Auction {
            get {
                return ResourceManager.GetString("StartingPrice_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status_Auction {
            get {
                return ResourceManager.GetString("Status_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title_Auction {
            get {
                return ResourceManager.GetString("Title_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title_Text {
            get {
                return ResourceManager.GetString("Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type_Text {
            get {
                return ResourceManager.GetString("Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor a Adicionar.
        /// </summary>
        public static string ValueToAdd_BidIncrement {
            get {
                return ResourceManager.GetString("ValueToAdd_BidIncrement", resourceCulture);
            }
        }
    }
}
